package io.github.jtpadilla.example.dagger.health;

public class HealthMonitorApp {

    public static void main(String[] args) {
        System.out.println("Initializing Health Monitor System...");

        // DaggerHealthMonitorComponent is generated by Dagger
        HealthMonitorComponent component = DaggerHealthMonitorComponent.factory().create("Production");

        HealthMonitor monitor = component.getHealthMonitor();

        // Run diagnostics multiple times to show different statuses
        for (int i = 1; i <= 3; i++) {
            System.out.println("\nIteration " + i + ":");
            monitor.runDiagnostics();
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
    }

}
